### ISSUE TITLE
Error: Face.distance(035dc6c4c40e7dc5df74da2a0d202234) target face no embedding!

### ISSUE THREAD

**Issue by zixia** [zixia/face-blinder#20]
```
[wechaty-blinder-1]2017-11-21T08:26:55.660824797Z 16:26:55 VERB Listener (message) onMediaMessage(青天会黄浦江论坛-facenet, MediaMessage<3266867166480538403.jpg>)
[wechaty-blinder-1]2017-11-21T08:26:55.660975247Z 16:26:55 VERB Listener (message) mediaFile(3266867166480538403.jpg)
[wechaty-blinder-1]2017-11-21T08:26:55.889629781Z 16:26:55 VERB Listener (message) saveStream(_, /workdir/blinder-docker/images/media-message-3266867166480538403.jpg)
[wechaty-blinder-1]2017-11-21T08:26:56.083389904Z 16:26:56 VERB Listener (message) onImage(/workdir/blinder-docker/images/media-message-3266867166480538403.jpg, MediaMessage<3266867166480538403.jpg>)
[wechaty-blinder-1]2017-11-21T08:26:56.181344718Z 16:26:56 VERB Listener (message) onImage() blinder.see() got 1 faces
[wechaty-blinder-1]2017-11-21T08:26:57.234266775Z Error: Face.distance(035dc6c4c40e7dc5df74da2a0d202234) target face no embedding!
[wechaty-blinder-1]2017-11-21T08:26:57.234304212Z     at Face.distance (/facenet/dist/src/face.js:374:19)
[wechaty-blinder-1]2017-11-21T08:26:57.234313551Z     at faceList.sort (/blinder/node_modules/face-blinder/dist/src/face-blinder.js:230:49)
[wechaty-blinder-1]2017-11-21T08:26:57.234320658Z     at Array.sort (native)
[wechaty-blinder-1]2017-11-21T08:26:57.234325364Z     at FaceBlinder.<anonymous> (/blinder/node_modules/face-blinder/dist/src/face-blinder.js:230:29)
[wechaty-blinder-1]2017-11-21T08:26:57.234330154Z     at Generator.next (<anonymous>)
[wechaty-blinder-1]2017-11-21T08:26:57.234333990Z     at fulfilled (/blinder/node_modules/face-blinder/dist/src/face-blinder.js:4:58)
[wechaty-blinder-1]2017-11-21T08:26:57.234338073Z     at <anonymous>
[wechaty-blinder-1]2017-11-21T08:26:57.234341905Z     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by zixia** [comment]
Try to fix this by https://github.com/zixia/face-blinder/commit/c5cd3fcdcc5f4a58a3c3b88f2c66f37e0d5c3c71
